development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: ms_base_development

test:
  adapter: postgresql
  encoding: unicode
  database: ms_base_test
  pool: 5

production: 
  adapter: postgresql
  encoding: unicode
  database: ms_base_production
  pool: 5